static char* xpm_lambo[] = {
"203 58 256 2 ",
"   c None",
".  c #000000",
"X  c #04060A",
"o  c #06080D",
"O  c #090A0C",
"+  c #090506",
"@  c #0C0D12",
"#  c #040B16",
"$  c #0C121A",
"%  c #121215",
"&  c #14151B",
"*  c #1A1A1D",
"=  c #17181D",
"-  c #12100F",
";  c #231A0D",
":  c #010D24",
">  c #010E29",
",  c #02122A",
"<  c #0B1728",
"1  c #141B24",
"2  c #1D1D23",
"3  c #141C28",
"4  c #031837",
"5  c #041138",
"6  c #201F25",
"7  c #16222D",
"8  c #1B222D",
"9  c #1F2025",
"0  c #182330",
"q  c #1D2935",
"w  c #182738",
"e  c #0A233B",
"r  c #222225",
"t  c #24252A",
"y  c #27282E",
"u  c #2A2A2D",
"i  c #29272A",
"p  c #242A33",
"a  c #2C2D32",
"s  c #232D3B",
"d  c #292C38",
"f  c #26313E",
"g  c #2C313C",
"h  c #2F3036",
"j  c #323235",
"k  c #34353B",
"l  c #3A3A3D",
"z  c #37383D",
"x  c #302F37",
"c  c #2A2415",
"v  c #001A45",
"b  c #001C4C",
"n  c #011646",
"m  c #001D52",
"M  c #001D5B",
"N  c #062648",
"B  c #192C45",
"V  c #012254",
"C  c #01235C",
"Z  c #072B57",
"A  c #063259",
"S  c #153658",
"D  c #1A3249",
"F  c #2B3543",
"G  c #2C3945",
"H  c #2B3B4B",
"J  c #253445",
"K  c #3C3D43",
"L  c #373A46",
"P  c #2A3C55",
"I  c #2C364A",
"U  c #001E62",
"Y  c #002465",
"T  c #022A65",
"R  c #00266B",
"E  c #002A6C",
"W  c #0A2B65",
"Q  c #04356A",
"!  c #163866",
"~  c #002672",
"^  c #002C73",
"/  c #012C79",
"(  c #01317B",
")  c #033676",
"_  c #143E7B",
"`  c #273F65",
"'  c #403F45",
"]  c #3D414A",
"[  c #2E4153",
"{  c #314255",
"}  c #364458",
"|  c #2F404F",
" . c #074178",
".. c #1A4670",
"X. c #2B4A6F",
"o. c #424245",
"O. c #43444C",
"+. c #48494D",
"@. c #4B4C54",
"#. c #474A55",
"$. c #4E515A",
"%. c #52545D",
"&. c #57575D",
"*. c #504F56",
"=. c #5B5C64",
"-. c #575A65",
";. c #4C5870",
":. c #5D626D",
">. c #5C6474",
",. c #63646C",
"<. c #676665",
"1. c #676A75",
"2. c #70737D",
"3. c #626163",
"4. c #003583",
"5. c #003C84",
"6. c #00378A",
"7. c #003B8B",
"8. c #0E3D82",
"9. c #013D93",
"0. c #003D99",
"q. c #0E3683",
"w. c #003FA1",
"e. c #054589",
"r. c #164787",
"t. c #014394",
"y. c #014B94",
"u. c #01449B",
"i. c #064A99",
"p. c #05549B",
"a. c #17599B",
"s. c #16548D",
"d. c #325490",
"f. c #326396",
"g. c #0044A4",
"h. c #014CA4",
"j. c #0046AB",
"k. c #004BAC",
"l. c #0A4CAB",
"z. c #0154A4",
"x. c #0053AD",
"c. c #005CAC",
"v. c #0759A8",
"b. c #004DB3",
"n. c #004EBA",
"m. c #0047B3",
"M. c #0053B3",
"N. c #005CB3",
"B. c #0052BC",
"V. c #015DBC",
"C. c #0A58B6",
"Z. c #1459A9",
"A. c #0763AC",
"S. c #0161B5",
"D. c #0162BC",
"F. c #0967B8",
"G. c #1667BD",
"H. c #166FB5",
"J. c #2E6DB4",
"K. c #1C60A4",
"L. c #4C6C90",
"P. c #767A85",
"I. c #6A7382",
"U. c #4F77B3",
"Y. c #014FC3",
"T. c #0054C3",
"R. c #0059C5",
"E. c #0056CA",
"W. c #005BCC",
"Q. c #085CC4",
"!. c #005DD3",
"~. c #005CD8",
"^. c #0163C4",
"/. c #016AC4",
"(. c #0064CC",
"). c #006BCC",
"_. c #0B66C6",
"`. c #186CC8",
"'. c #0073CD",
"]. c #0577C9",
"[. c #1675C8",
"{. c #0063D3",
"}. c #006CD3",
"|. c #0064DA",
" X c #016BDB",
".X c #0B67D9",
"XX c #0173D4",
"oX c #007AD3",
"OX c #0172DC",
"+X c #057BDA",
"@X c #1479D7",
"#X c #156BD9",
"$X c #2978CE",
"%X c #006CE3",
"&X c #0069E4",
"*X c #0072E4",
"=X c #007CE3",
"-X c #0074EA",
";X c #007CEC",
":X c #0C79E3",
">X c #007DF0",
",X c #167BE4",
"<X c #1673E0",
"1X c #73839C",
"2X c #0883DA",
"3X c #1584D5",
"4X c #2D88D6",
"5X c #0184E3",
"6X c #0084ED",
"7X c #008CEC",
"8X c #088AE6",
"9X c #1889E6",
"0X c #0092EE",
"qX c #0797EE",
"wX c #0084F1",
"eX c #018CF2",
"rX c #0A8DF1",
"tX c #0194F2",
"yX c #019AF4",
"uX c #0C9BF4",
"iX c #0796F5",
"pX c #189BF4",
"aX c #1797ED",
"sX c #3796EA",
"dX c #289BF4",
"fX c #379DF4",
"gX c #2E8EE8",
"hX c #3AA3F4",
"jX c #29A1F4",
"kX c #1EA0F4",
"lX c #4B8ED1",
"zX c #4999EE",
"xX c #47A4F5",
"cX c #58A8F5",
"vX c #56A5E6",
"bX c #67ADF6",
"nX c #6AB2F6",
"mX c #79B5F7",
"MX c #6DABEE",
"NX c #71A2D7",
"BX c #888C98",
"VX c #ABADB6",
"CX c #959CAD",
"ZX c #88BAF7",
"AX c #92BDF6",
"SX c #8DB2E7",
"DX c #9AC3F7",
"FX c #92C1F4",
"GX c #A8CAF8",
"HX c #B9D4F9",
"JX c #B1CFF6",
"KX c #C6DBF9",
"LX c #D6DBE6",
"PX c #D7E5FA",
"IX c #CEE1FB",
"UX c #E8F1FC",
/* pixels */
"                                                                                                                                                                                                                                                                                                                                                                                                                      ",
"                                                                                                                                                                                                                                                                                                                                                                                                                      ",
"                                                                                                                                                                                                                                                                                                                                                                                                                      ",
"                                                                                                                                                                      n.n.Y.n.Y.Y.Y.Y.T.Y.T.E.T.E.E.Y.T.Y.n.n.n.n.j.j.w.                                                                                                                                                                                              ",
"                                                                                                                                                  n.E.!.!.!.!.|.|.|.|.{.{.}.*X;X6X6X6X6XwXwX7X6X6X6X6XwXwXeXwX>X-X|.|.|.!.~.E.T.n.m.g.6.                                                                                                                                                                              ",
"                                                                                                                                    T.!.~.|.{.!.E.5XwX6X7XwX7X6XeX7X7X7X6X7X6X6X5X8X6X8X9X9X8X2X9XaXrX7XrX7XeXeXeX7XeXeXeXwXeX7XwX%X|.!.E.Y.j.9.A                                                                                                                                                                     ",
"                                                                                                                        W.(.}.R. X X%X7X6X2XrXtXeX6X5X2XS. .....S 4 D P J e 3 < < 3 8 t q q q q 0 q 8 8 3 3 < 7 D [ { ..X.s.F.9X7X7XtXrXeXwX%XT @ @ o #                                                                                                                                                               ",
"                                                                                                            r._.l.^.{.*X*X-X;XeXeXtXeX5X].s.! D e 7 $ o @ o % 2 p p d s g k f F H H H P H | | | P H | H { | P P | J H G J J f s w X...K.[.8XtXeXoXc.Z # o X o                                                                                                                                                         ",
"    %.@.-.@.1.    =.1.1.                                                                        R.h.|.|.%X*X*X-X;X6XwXeX0XtXtXyX].a.A K +.6 2 % X . o 1 f z | f G G L G F g 8 H H | H H H H H J G G H H H I H H P P [ [ [ [ [ [ [ | H w F G ..K.[.8XrX5XF.Q 4 O o                                                                                                                                                     ",
"        =.=.=.,.,.,.,.,.,.,.-.=.,.@.o.' *.z a                                       `.{. X%X%X-X-X=X;X6X6XeXeXiXtXuXuXtXyX].a.< & i o.r % 2 1 o @ p z G f f f | G G G G f g f I G G w 0 7 0 0 0 0 0 0 7 0 0 0 0 0 0 8 0 D J H | [ { { [ [ [ ] w L [ s.H.2XrX0X].A 4 o X                                                                                                                                               ",
"            6 @.-.-.:.1.,.1.% k -.%.2.2.@.k = O                       Q.!.{. X&X*X-X;X-X;X;X7X6XeXtXiXuXpXjXjXqXyXyX2XA.o o % * z & % % i % o 2 s f g f 0 0 7 g F F F F d 0 F H H H 0 7 0 0 0 0 0 0 0 0 7 0 0 7 0 0 0 0 0 0 0 0 8 0 s H | { [ [ { { [ 0 { w J.2X8X7XoXN , X                                                                                                                                           ",
"                  & r       % a                           R.!.|.&X%X*X-X-X;X;X;X;X6XwXeXeXtXuXpXhXcXcXxXpXyXyXqXF.A $ & = r r a * @ & d o + 2 p f s f s 0 7 q f f f J p p 1 H H H w 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 s P [ { { { { } 1 g B J.3XrXiX2XA # o                                                                                                                                     ",
"                    r         a             $X#XW.|.&X%X-X-X-X;X;X;X>X;X6X7X0XyXtXtXpXjXcXnXnXnXcXjXqXyXqXqXv.4 N N 4 3 i a l l - & r O + 2 8 q q q f 0 0 0 0 s s s s 3 3 q G J J q 0 0 0 0 0 7 7 0 0 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 J [ { [ [ [ | 8 s D J.gXrXiXF.e o X                                                                                                                               ",
"                    % P.      X.lX@X@X:X X|.%X%X-X-X;X;X;X;X;X6X7XtXtXtXtXyXkXhXcXmXmXmXmXnXcXxXkXyXqXaXe.V E 4.t.j.M.B.R.B.e.! 3 t @ X = 1 8 p q q q 7 0 0 0 q s s 8 3 1 f f f f 7 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 7 0 0 J H H P [ g p 2 3 X.J.gXaX2Xp., #                                                                                                                           ",
"            X.8 d P N ! e.F.[.+X=X=X=X-X*X;X;X6X;X6X6XeX7XrXrXaXjXjXhXcXnXmXFXmXmXmXmXnXbXcXxXhXjXkXuX2Xe.h.M.T.W.{.{.|. X X*X*X-X/.p.) A 2 = 1 7 8 0 q q 7 0 q q 0 1 1 1 s q q w 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 q G w 0 0 7 0 0 8 0 J I H s 8 J J q 1 B X.$XsXdXG. .$ o                                                                                                                     ",
"          G.C.S.).J.f.7.v./.). X*X;XwX7XdXfXcXbXnXZXDXDXGXJXJXHXJXGXGXDXFXZXmXmXnXbXcXxXhXfXhXjXjXkXkXkXuX2X5X}. X*X-X=X=X;X;X;X;X;X=XOX).^.z.e. .S 7 9 7 7 7 7 7 3 & & 7 8 7 7 0 0 7 0 0 0 0 7 0 0 0 0 0 0 0 0 0 7 0 0 7 0 0 0 0 0 0 0 7 J J f { -.>.$.L { | } H I p 1 g I F f 8 3 < [ f.cXhXgXK.N o                                                                                                                 ",
"          d.J.J.'.+XOX4X@X@X=X6XaXhXbXFXGXJXJXHXHXKXKXKXKXKXHXJXJXGXDXFXZXmXnXMXcXvXhXjXkXqXqXyXyXuXqXuXuXpXuXuXqX0X0XyXyXyXyXyXyXtXyXyX0X5X2X5X2XoX+XF.v.r. .D q 7 $ & 0 7 1 7 7 0 0 q 0 0 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 s f D -.BXBXBXBX:.] O.K G F 2 3 s f f s q 8 $ 1 < d.lXcXxX$X..o O                                                                                                           ",
"            1.;.a.+XOX}.XXXX@X8XfXGXPXIXPXPXPXPXPXPXKXLXHXHXJXGXDXAXAXmXnXMXcXxXhXjXpXaXyXyXqX0X0X0XtX0XyXqXyXyXyXyXyXyXyXqXyXyXyXyXyXyXyXyXtXtX0XqXtXtX7X0X5X2X2X2X].v.Z.a. ...! D w w 0 0 0 7 0 7 7 w 0 0 0 7 0 0 0 0 0 0 0 0 7 0 0 0 7 0 7 w ..f.U.L.BXCXVX1.,.%.O.F p q 0 q 8 0 8 7 1 $ - $ P U.MXcXsXK.4 #                                                                                                       ",
"            2.,.>.A.+XXX}.}.}.}.oX3XvXGXPXIXKXKXKXKXHXHXGXDXDXFXZXmXbXcXvXhXdXaXqX0XqX0XtX0X0X0X0X0X0X0XyX0X0X0XqX0XyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXqX8XqXyXyXyXtXtXeX0X0X0X2X5X5X5X5X].F.H.s.....D w w w 7 7 7 7 0 7 7 0 8 7 0 0 0 7 7 = 7 7  .A.S.c.t.9.i.r.8.r...X.I 3 7 1 1 1 1 1 1 = % % @ 3 ! 4XxXfXdX_.A Z ~                                                                                                 ",
"          2.,.x i ;.[.oXXXXX}.}.).)./.2X4XDXGXGXFXFXSXFXFXFXSXmXMXcXxXfXqXyX0X0X0X0X0X0X7X0X7X0X0X0X0X0X0X0X0X0X0X0X0XyXqXqXyXyXyXyXyXyXyXyXyXyXyXyXkXuXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXiXyXtXyX0XyXyX0X7X0X7X2X@X[.s...[ D w e 0 3 < $ < # # 7 7 N  .5.7.7.0.g.g.g.m.m.Z # $ & $ $ $ $ $ # $ , Q @XiXiXpXdXhXxXzXxXzXzXzXsX#X.XlX(.!.Q.n.n.                                                                            ",
"            p 2 % u B XXXX'.}.).).).).).).{.vXAXMXbXvXbXbXcX@XC.C.C.).5X7X7X7X0X0X0X0X7X7X7X7X7X7X7X0X0X0X7X0X7X0X7X0X0X0X0X0X0XqXqX0XyXyXyXyXyX2X9XqXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyXyX0XyX0X7X0X8X2X4XJ.X.[ J < q ) 4.t.u.9.6.0.w.9.e % o @ @ @ o # # D H.qXyXiXuXxXbXmXZXmXbXbXbXbXbXmXmXmXZXZXbXsX.X<X`.Y.Y.w.                                                                      ",
"              y * = 2 X.+X'.).).(.).(.(.(.(.(._.(._.b.m.h.j.j.j.k.m.j.b.m.B.B.=X7X6X7X0X7X7X7X7X7X7X7X7X0X7X7X0X0X0X7X0X0X0X0X0X0XyXqXuXqXaXuX8XXX7XyXyXyXyXyXuXyXyXuXyXyXyXuXyXyXiXiXyXiXiXuXiXqXyXuXuXuXuXpXpXkXpXdXkXkXdXdXhXjXjXhXhXhXhXzXsXsXgXgXMX4Xp.( 4.0.! I 0 $ # 7 S H.2X9XaXyXdXbXZXDXJXHXKXIXIXIXKXJXAXZXmXZXAXAXAXGXGXGXAXbX.X:X,XE.n.0.                                                                ",
"            & k %.6 * * p.XX).}.).(.(.(.^.^.R.M.j.g.g.0.7.4 , : : : , M 9.j.k.m.B.XX6X6X7X6X5X5X7X6X6X7X7X7X7X6X7X7X7X0X0X0X0XtX0X0X0X0X=X=X=X*X{.{.{.{. X}. XOX*X8XdXdXdXhXhXhXxXfXfXxXxXxXxXxXxXxXcXxXxXcXcXcXcXbXcXbXbXbXnXbXnXmXmXmXmXmXmXmXnXMXmX[.7.( 4.0.G.NXSXAXMXvX4XkXhXhXjXnXAXGXGXHXHXKXKXIXPXPXPXUXUXPXIXKXJXAXAXGXJXKXKXIXKXKXGXcX:X-X%XR.n.0.                                                          ",
"        l.w & a O.a y t 8 C.oX'.(.(.^.^.^.B.j.g.t.C > X . + + O + O + . + o 5 ^ j.b.V.OX+X=X=X=X+X=X5X5X5X5X7X5X7X7X7X6X0X7X6X5X=X+X*XOX*XOX*XOX_.W.W.{.}.(.XX X}.{. X{. X.X X:X,X9XsXxXxXcXbXbXnXnXmXmXmXmXmXZXmXmXZXZXZXAXAXAXDXDXDXDXGXGXDXGXDXvXA.4.( 4.z.C.b.T.(.lXvXzXbXlXbXmXDXDXFXZXAXZXZXZXZXZXmXcX$X<X#X.X.X.X#X#XgX4XMXDXKXPXUXUXUXPXHXmX,X-X&X&XY.Y.                                                      ",
"      $X$XJ.J.`.).}.].4XNXNXH.oX).).^.R.k.h.t.V X . O = i j l l K l l j i - + . : ( j.b.(.OX XOXOXOXOX=X=X=X5X=X5X;X=X*XOX XOX X}.|. X X X|. X Xl.W.W.V.T.R.W.{.{.}.{.}.OX}.{.|.|.|.|.|.|. X X@XgXgXzXvXbXMXZXZXAXAXAXGXAXGXGXGXGXGXJXJXJXJXJXJXlXz.( ^ i.v.t.t.j.B.!.%X@XvXGXzXfXfXgXdXdXaX9XrXeXwX;X%X|.~.m.u.E Z E T C ( h.B.~.~.zXAXIXUXUXUXUXUXHXbX9X-X-X&X~.Y.                                                  ",
"      J.`.].oX+X5X5X2X3X9X3X+X'.'.)./.h.g.^ # + O 2 k l l l j j x x j ' l o.j 6 + . n j.b.T. X}. X}. X X X X X}.}.{.{.{.{.{.{.{.{.{.{.{.{.{.{.|.XXB.E.R.T.V.^.b.Q.B.R.R.R.R.(.!.!.{.{.{.|.|.|.|.&X~.|.|.|.&X&X|.,XsXzXzXcXMXbXZXZXZXSXAXSXAXSXSXG.y.6.6.6.9.0.g.n.W. X@X9X9XgX:X-X;X;X;X-X;X>X;X-X&X!.B.( + . + O - % & % O + + 5 6.m.E.).[.[.lXlX1XNXFXZXhX<X&X-X-X.XY.                                              ",
"      J.`.'.oX+XoXoXoXoX].oX].'./.D.j.g.E . . % j l k k L o.&.&.%.&.*.F l l l ' k = + # 9.m.B.R.W.W.(.W.W.W.W.(.(.W.{.!.{.!.(.!.{.W.!.(.(.!.!.{.{.C.R.E.E.R.W.W.W.{.W.W.R.R.W.!.W.!.!.!.{.{.~.{.~.|.|.|.|.|.|.|.|.|.|.|.~.|.|.|.|..X,X,X,X$X$X(.m.k.j.j.g.j.m.B.W.}. X*X-XOX(. X X*X%X*X&X-X%X&X~.T.Y + + - r j l o.o.o.o.l j i * O # 6.W.~.;XeXtXtXkXxXmXmXcXdX*X{.&X&X&XY.                                          ",
"      J.H.].oX].oXoXoXoXXX'.'.).D.g.g.Z . + i j k k l =.] K a j ' x x ' @.@.i l l o.r + . 7.m.M.T.T.R.R.R.E.W.R.W.W.W.!.W.(.W.W.W.W.W.!.!.(.!.{.|.x.B.T.T.R.E.R.R.R.W.W.R.W.W.!.W.!.!.!.W.!.!.!.!.!.{.|.!.|.|.|.|.~.|.|.~.|.|.!.!.!.E.E.T.Y.b.j.j.g.b.b.B.R.T.R.W.{.|. X X XB.|.&X&X&X&X&X&X|.{.9.o + % u o.o.] l l i u u l l l l j 6 + # j.~.*XwXwXeXeXeXiXpXuXyXwXa.Z.n.~.&XE.E.                                    ",
"        G.].].'.XX'.XX'.'.)./.D.h.w.C . + i k k K =.O.K @.a 2 O - ; c c k L @.+.u l o.r + X 7.m.B.B.B.T.T.R.R.R.R.E.R.R.W.W.W.W.W.W.W.!.{.W.{.{.!.(.j.B.B.B.T.B.R.R.R.R.E.R.E.R.W.W.E.R.E.!.!.W.!.!.!.!.!.!.!.!.~.!.!.!.!.!.!.W.E.E.T.Y.n.m.j.m.j.j.j.j.b.B.T.R.W.!.~.~.~.~.j.|.|.|.&X~.&X~.~.) . + r o.o.l a ] o.+.k k l +.*.O.i l l j = . 7.!.&X-X>X>X>XwX>XwXwXwXeXwXs.B S h.~.~.g.                                ",
"        J._./.'.'.'.'.'./././.k.g.4.+ . i j h $.=.2 @ & @.@ o o O ; ; ; K 2 @ a @.j l o.r + # g.k.B.B.B.B.T.T.B.R.R.R.E.R.R.R.W.W.W.R.!.W.{.W.{.W.!.C.M.b.B.B.B.B.B.T.B.T.T.R.R.R.R.E.R.E.E.E.E.W.W.W.!.!.W.W.!.!.W.W.W.!.!.E.E.E.T.B.n.b.m.k.j.j.j.b.n.B.T.E.E.!.~.!.|.!.E.g.|.|.|.|.|.~.E.W . O u o.K u o.K r - i l r u #.+.y o.@.j l k r . Z !.&X-X-X-X-X-X>X>X>X>X>X>X-Xr.F I X.C.m.                              ",
"        J.H.F.'.'./.)./././.V.u.u.# . * a j L ] & @ o o a :.& @ X ; ; ' a o o @ r ] j o.o.& + v j.m.B.n.n.B.B.B.T.T.T.T.R.R.R.R.R.R.R.W.W.W.W.W.W.W.^.j.b.b.b.M.n.M.n.B.B.B.B.B.T.T.T.R.R.R.T.E.R.E.E.E.E.E.W.W.E.W.E.E.E.E.E.T.T.B.n.n.b.b.m.m.m.b.n.n.T.E.E.E.!.E.!.~.~.E.g.!.|.~.~.~.W.Q . - j o.k l ] l - + + + K @ X O o 2 *.h O.K a l 6 . ^ W.|.-X-X-X-X>X>X>X>X>X;X>X>XOXf.I I P ..B.                          ",
"        L.A.S.D.'.)./.)./.D.h.g.C . % u j %.K k 2 o o @ O $.@.@ 2 t ' L X < $ o & k +.r o.l O . ^ j.b.n.B.M.B.B.B.V.B.B.T.T.T.T.R.R.R.R.R.W.W.R.W.W.W.K.k.b.b.b.m.b.b.n.b.B.n.B.n.B.B.T.T.B.T.T.T.R.R.R.E.T.R.E.E.E.E.T.E.R.T.Y.T.n.n.n.n.b.b.n.n.n.n.T.T.E.E.E.!.E.W.!.E.T.0.!.!.|.!.!.M.X . u o.j l j t l o O - % O.#.% o X X + 9 j K O.j j * . t.~.%X-X-X-X-X-X>X-X>X>X;X>X>X;X`.X.g L I s.                        ",
"  =.3.,.,._ t.N./.).)././.V.g.u.o . r a u 2.$.a O.@ O o @ a #.x & k $.6 $ S ! n x a x ' ' +.r + : g.k.b.b.b.b.M.n.B.B.B.B.T.B.B.R.T.R.R.R.R.R.R.R.R.R.Q.x.k.k.m.k.b.k.b.k.b.b.b.b.M.B.n.B.B.B.B.n.T.B.B.T.T.B.T.R.T.T.T.T.T.T.T.n.n.n.n.n.n.B.n.n.T.T.T.T.E.E.E.E.!.E.~.E.Y.g.W.~.!.E.E.N . i l o.j k u @ %.t y L l j 1.K g 9 @ ] ] h & &.+.j j O # n.~.%X%X*X*X&X-X-X-X-X-X-X>X>X-X*Xa.w } P {.^.                    ",
"  ' O.O.g @ T i.D./.^./.V.M.z.T . O h k 2.O.G @ K o.o 2 L a #.' t k F & r.r.9.#.k X d *.i ' l - . E g.m.m.b.b.b.b.b.b.b.M.B.B.B.B.B.B.T.T.T.E.R.R.E.R.R.i.x.x.x.x.x.k.M.M.b.b.b.b.b.b.b.b.B.b.b.n.n.n.B.B.B.n.n.n.B.n.Y.Y.n.n.B.n.n.B.n.n.n.n.B.Y.T.T.T.E.T.E.E.E.E.E.E.T.Y.j.!.W.W.E.g.. - j ] j k u < ) a *.k K o.t -.] z r >.&.9 X & = ,.j j u . Y s._. X X X-X%X-X-X-X-X-X-X-X-X-X-X*XC.i. X|.W.                  ",
"    l K g 2 O V x.^././.D.k.h.4 . 2 j j P.1.= @ 2 %.y r 6 y k ' L ' F & l.! d.#._ : @ L +.o.+.2 . 4 g.j.k.m.k.b.b.b.b.b.b.b.b.M.M.B.B.B.B.T.B.R.R.T.R.B.T.y.x.x.M.x.M.x.x.M.M.x.M.b.k.M.b.b.b.b.b.b.b.b.b.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.B.n.T.Y.T.T.T.E.T.E.E.E.T.Y.m.m.E.E.T.R.N . u o.l k a & e.R.t $.j k K y #.k y O.$.] 9 o o 9 y $.a j @ X L.I.;.L.L.J.(. X%X&X%X*X&X&X-X-X-X-X*X-X*XOX}.(.                ",
"      l L s 2 o Q V./.^.V.x.x.X + i h :.L L o X o L $.p & 1 ' ' x k ' r 8.I ' d.r.S O ' O.+.+.i o X u.g.k.j.j.k.k.k.k.k.k.b.b.b.b.b.b.b.B.M.B.B.B.T.T.B.B.M.z.v.c.c.c.x.N.c.x.M.x.M.M.M.x.M.M.M.b.M.b.b.M.b.b.b.b.b.b.b.m.b.b.n.n.b.n.n.n.n.n.n.n.B.T.n.Y.T.Y.E.T.E.T.T.Y.b.k.R.E.T.T.X + j +.a h r N Z.V.e.] ] j O.a x j t L z k k * + @ 7 ] p j r . T V._.D._.`. X|.|. X&X X X X&X%X%X%X%X%X*X*X X}.(.              ",
"    O.+ u K g t 4 i.V.^.N.M.5.. + u h BX:.& X o % = x ,.-.,.-.$.L ' $.' F ' U.Q.i.e.o @ O.u ' j O . Q h.j.j.k.k.b.k.b.k.b.k.m.k.b.b.b.k.b.M.n.b.n.n.B.B.n.B.5.z.c.c.c.c.c.c.c.c.N.N.N.M.N.c.M.M.M.M.M.x.M.M.b.b.b.b.b.b.m.b.b.m.m.b.b.b.n.n.b.n.n.n.n.n.Y.T.B.Y.Y.T.Y.Y.n.j.g.T.T.T.Q . & ] o.j u & 5.(.|.Z.u K j 1.K k j k p j k l h - ] l 9 %.a i + : W.{.|.|.}.|.|. X|.{.{.{.{.{.{. X XOX%X X&XOX}.}.^.F.          ",
"    r y ' 2 o.o.k p t.M.N.v.Q . - j j P.$.$ o O % & % r L $.a 1 t i 2 ' K _ $XC.i.r.o @ 2 6 l o.% . V h.h.j.k.h.k.h.h.b.h.k.k.k.k.k.k.b.b.b.b.b.b.M.M.b.b.b.b.y.z.z.z.z.c.c.c.c.c.c.c.c.c.N.N.N.N.N.N.N.M.M.M.M.M.M.M.b.M.M.b.M.b.M.M.m.m.m.m.b.n.n.n.n.n.n.n.n.n.Y.Y.Y.n.j.u.T.B.T.V . r o.j h i % H L P  .= %.a k & y @.@.2.a h t 8 $.#.@ @.2.i u O . B.{.|.|.|.|.|.{.{.{.{.{.{.{.{.{.{.{.b.{.}.R.^..X).(.C.        ",
"      6 6 i @.,.=.%.2.$.q < , . = j K ,.%.o o = @.=.BX,.y 2.#.@.& 6 i ' t d.d.U.Z.r.: O a k l o.* . 4 h.x.h.k.x.k.h.k.h.x.k.x.x.x.k.M.M.x.x.^.M.u.t.i.i.C.F.M.( ( 4.5.p.p.c.c.A.c.c.c.c.c.c.c.c.c.N.c.N.N.c.N.N.N.N.x.M.M.M.M.M.b.M.x.b.b.k.m.b.m.m.b.n.b.n.n.n.n.n.n.n.m.w.t.n.B.R.e . j o.u l a k } X.{ L k 9 j 6 j 2 2 $.o.x y $.:.k o o <.%.j j & . y.!.|.{.|.{.{.{.{.{.(.{.(.{.{.).{.{.{.}._.r.h.D.D.v.V.F.      ",
"        6 6 2 3.<.&.K K K K - . = j K -.O.a d O.K #.%.L -.=.#.j 3.6 i i x x F I O.P F o i l l l * . , h.z.k.h.x.x.x.M.x.M.x.x.x.V.^.oX+X5X5X6X5X8X9X@X#XG.C.Z.a.W R R R E ^ ^ ( 5.y.p.c.c.c.c.A.c.c.c.S.S.S.N.N.N.N.N.N.N.N.M.N.M.M.M.M.M.M.M.b.b.M.b.b.b.n.b.n.b.n.b.m.m.w.9.n.R.R.o . j o.i t @ < _.{.j.C.h h = 2 j r k 2 #.p O.] k u X . ] o.i a * . ^ W.{.{.{.{.|.{.{.{.{.(.{.{.W.{.{.(.(._.J 9 J ! ( i.Z.Z.      ",
"          a & i ,.,.' K l K % . & j l %.a 9 2 o 2 % % a #.K d L r d t 6 k L 9.lXJ.` a d 2 l l l = . , z.z.x.x.x.c.x.h.D./.^.=X5X5X=X=XOXOXOXN.i.W Z b b n b n M C C R Y Y T Y R R E E ~ ^ 5.5.y.p.z.A.c.S.A.c.S.c.N.c.S.c.S.N.N.N.N.N.N.N.M.N.M.M.M.M.b.M.b.M.b.b.b.n.b.k.0.9.V.D.^.. . k o.r y % 4 _.{._.x.P.6 k a y <.r % L ' r 9 t r X X 2 a i j & . N W.{.{.{.{.{.{.{.!.(.(.(.{.(.W.(.W.Q.q 2 i y 6 J W 4.t.      ",
"            * i i &.=.' ' ' = . % j k 1.$ X X X & 2 x d :.I.-.-.L ' p L x ' G.J.l.r.: 6 k d l l = . , p.z.v.x.N.D.).+X=X=X=X+XOXOX X XD.) 3 = = & 5 n n n m M M Y C C Y Y R R Y Y Y Y Y T Y R R R R E ^ 5.e.y.y.p.c.c.c.S.c.S.c.S.N.N.N.N.N.N.N.N.N.V.N.M.M.M.B.b.M.b.b.m.u.t.V.^./.. + j o.i i $ B K..Xl.M.t a 2 * i r L j x t j p i p X X 9 u r a * . 4 (.(.{.{.{.{.!.(.(.W.(.(.W.W.(.W.S.J r 8 r i 6 t v ^ e.      ",
"          P.i + + @ &.' ' ' 6 . - j k CX9 O X @ & 1 x @.P.*.%.%.6 #.' a L k G.K.8.! o # k i l l = . , t.7.h.N.M.M.N.N.N.N.R.(.}.}. X}.N.! s 1 & & 5 5 n m M M U Y Y M M Y Y Y Y Y R Y Y R Y Y Y T Y R T R R R R E E ^ 4.t.t.i.p.p.c.c.N.N.S.N.V.N.S.N.N.V.N.N.V.N.M.M.M.x.i.y.D.D.V.. . a o.i k d f s._ _ S L +.y y ' k y u y k a L +.L $ X 2 r i h % . 4 {.{.{.).{.{.(.(.).(.).(.(.(.^.F.B i 6 r r 6 6 1 m E e.      ",
"            VXBX+.j +.3.' K i . + a l BX1.- X & & 2 $.#.*.x -.+.#.%.L L d ' X.8 ! B @ 2 L l ' i & . , 4.6.6.4.4.4.( ( ( ^ ^ ( e.t.h.M.T.^.}.[.s.S N n n n M M M U U Y M M Y Y Y Y Y Y Y Y Y Y Y Y Y R T R Y R Y E E E R R E ~ ~ ^ ^ / 5.y.t.z.z.N.N.N.S.N.S.N.N.V.S.N.N.M.p.p.V.D.D.. . i o.j l j a g x s ! w @.x t k x #.O.L j a k k k #.x % 2 i u - . 4 {.{.}.).(.(.).(.^.(.(.(.(.^.N.B r 2 2 6 2 6 = : v C (       ",
"                VXVXBXP.+.o.u . . a k l LX& y x y ' F 6 j L $.k L %.F x a x a x p & o 2 k l l i o . 4 7.6.6.4.4.4.4.( / ( ^ ^ ^ ^ ^ Q ^ ^ ( t.x.^.@XsXJ._ W m M U U U R R M b m C C C n n b V C M M M C Y Y Y Y Y R R R R Y R R R R R E ~ ~ ~ ^ ^ ^ ( t.t.z.c.N.S.S.V.S.N.p.p.D.V.D.. . * l l i = & p Z._..Xi.2 x $.+.O.O.L $.j a j a o @ d k 9 i u O . 4 }.{.(.$X X}.).(.(.^.^.^.^.D.B r 6 2 2 2 = = : v R 0.l.      ",
"                  c &.CXP.*.u . . & j k L d 2 2 @ O X 2 L k L = L ' -.6 2 L y & i 9 d -.i l l 6 . + V 7.6.6.4.4.( ( ( ( ^ ( ^ ^ ^ E E E E E Y T Y T T ^ 9.$XMXlXf.U U U U R R R ~ ~ ~ R ~ ~ R ~ ~ R ^ ( ^ C m m W 8.E 5 5 n n m C Y Y E R R E E ~ E ~ / ^ ^ / / / / 6.t.t.p.p.S.S.V.. . + l l i 2 = % S _.%XM.$.K @.o.L g l @.1.k j & O o @ z t a i . . 4 }.{.{.{.W.W.W.|.>X*X}.V.R.A = 2 2 & * 2 & > n 4.j.n.T.      ",
"                    % % r =.O.+ . + j x x VX' 2 @ o X O % p j 2 K ' k x y 2 @ o O & r o.o.l i % . . m 6.6.4.4.4.4.( ( ^ ^ ^ ^ Q E E E E R R T T T Y C C M W C W / r.K.lX4XV.n.n.C.M.k.g.0.6.4./ / / ~ ~ ~ ~ ~ ~ ~ ~ R R ~ R ~ R R R R ^ / R M R _ _ Q M n 5 n n m Y R ^ ^ Y  .D.S.D.4 . . a l k i 2 @ N `.).J K @.@.o.a ,.k a ] k 2 @ O O & r u u % . . V XX X}.}.}.).{.(.(.(.{.-X:X_.W * & % = 1 5 C 6.m.T.E.W.Q.    ",
"                        - - 2 6 + + r x L BXI.L % O o O @ p % & y x x 6 @ o o o % t k l o.l u + . . ( 6.6.6.6.6.4.4.4.( ( ( ^ ^ ^ E E R T T Y Y C Y C C M M M Z M m V M Z _ q.8.$X@X|.|.|.|.|. X{.{.{.W.Q.R.R.(.(.R.D.V.h.9.7.4.~ / ~ / / / ~ ~ ~ ~ ~ ~ R ~ ^ / ( E T Y R Y E 7.9.t.v . . % j l u r 2 o X.Z.k K @.*.' u :.o.K z x y & @ & i 9 a u . . . 5.XX}.}.}.}.}.}.{.{.).}.{.).!.&X(.i.v N Y 4.6.g.T.R.W.!.(.    ",
"                                  -   u j k &.$.g % @ o O g @ o o o x y o o o & i k h k l j % . . . 4.6.6.6.6.6.4.5.4.( ( ( ( ^ Q ~ E R E T T T C C C C C V V m m V b b b b V b V m E Q ^ 5.7.7.9.9.9.u.i.k.M.R.(.}.{.}. X|. X X X X{.{.(.(.Q.V.R.^.`.`._.Z.g.7.6.6.4.6.q.R E 6.6.6.V . . . j l j u t 2 @ 0 y 8 +.@.j t K +.9 % @ 2 t d j a u u % . . . c.XXXX}.}.}.}.}.}.}.).}.}.).).).).{.W.W.T.T.E.!.{.{.}.).(.    ",
"                                        j j k k ] a 2 = o u         y X + @ 2 y k j k l u r . . . # 7.7.7.7.7.7.4.4.4.( ( ( ^ ^ ^ Q E E E T C C C C V V V V b m b b b v b v v v 4 v v n v 4 v v v v v v b v v b b b b b m m V V Y Y R Q ^ E ^ ( 4.e.t.t.t.t.u.h.v._.`.`._.b.7.( 4.4.E         l k k y 9 1 2 2 @ o & t r h y       9 & a a u h *     . X XXXXXXXX}.XXXX'.}.).XX).).).).).).).).(.(.}.XXXX).).[.`.`.    ",
"                                          a j k a ] ] k r t &       a   2 g x k j l l j j           y.y.y.y.y.y.y.y.y.y.y.y.e.e.e.e.e. . . .) ) Q Q Q Q Q A Q A A Z Z Z Z N V N N N N N N N e e 4 , , , > , , , , , , > : : > : > > , > > > > > , , , 5 , 5 5 5 5 5 5 4 5 v v v b V Z           j k u i i y 2 O o X % 9       z o.x K j u u r         N oXoX}.}.XXXX}.).}.'.'.'.}.XX{.).)././.D./.F.A.A.              ",
"                              . . . . . . + j k k u L +.k t d 2 6 2 y L =.L x j k l j j . . . . . . . . . . . . . .                                                                                                                                                                               j j h y a ] h 2 % = 8 d P.I.] $.L a a u 2 . . . . . ) D.D.D.D.D.S.c.c.c.z.z.p.Q , # # # X                           ",
"                  . . . . . . . . . . . . . . u j j k j O.K 1.2.P.,.o.*.y k j l k r i . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .             . . . . . . . + j h j a 9 o.] ] a a -.:.$.$.a u u u r . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .           ",
"                . . . . . . . . . . . . . . . . 9 u j j k k k k k k j j k j j i u . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . r u u a u h r = & % 2 u i y u i & . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .           ",
"                  . . . . . . . . . . . . . . . . + r u j j k h j j k j a r O . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . - 2 u u u a u i u u i 2 + . . . . . . . . . . . . . . . . . . . . . . . . . .                               ",
"                                  . . . . . . . . . . . . + + + + + + + . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . + o + + o + . . . . . .                                                                               ",
"                                                        . . . . . . . . . .                                                                                                                                                                                                                                                                                                                                           ",
"                                                                                                                                                                                                                                                                                                                                                                                                                      "
};
